language: julia
os:
    - linux
    - osx
julia:
    - 0.4
    - nightly
script:
    julia -e 'Pkg.clone("https://github.com/lpsusu/lplib.git", "LPLib")'
    julia -e 'Pkg.test("LPLib", coverage=true)'
after_success:
    - julia -e 'Pkg.add("Coverage")'
    - julia -e 'cd(Pkg.dir("LPLib")); using Coverage; Coveralls.submit(process_folder())'
