language: julia
os:
    - linux
    - osx
julia:
    - 0.4
    - 0.5
    - nightly
script:
    julia -e 'Pkg.clone("https://github.com/lpsusu/Drs.jl.git", "Drs")'
    julia -e 'Pkg.test("Drs", coverage=true)'
after_success:
    - julia -e 'Pkg.add("Coverage")'
    - julia -e 'cd(Pkg.dir("Drs")); using Coverage; Coveralls.submit(process_folder())'
